### ISSUE TITLE
Upgrade to babel v6

### ISSUE THREAD

**Issue by marcelklehr** [redux-effects/redux-effects-cookie#2]
hey, you're doing some awesome work here.

Could you update your babelrc files as well as the version on npm to the latest version of babel? I'm getting some errors when trying it in babel v6

Thank you :)

**Comment by ashaffer** [comment]
Done :). Let me know if this fixes your errors - I don't think it should have made any difference, but either way it's up to date now.

**Comment by marcelklehr** [comment]
Thank you! Keep up the good work! :)
